#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
    path: /
    controller: App\Controller\AppController::index

about:
    path: /a-propos
    controller: App\Controller\AppController::about

index articles:
    path: /articles
    controller: App\Controller\ArticlesController::index

view:
    path: /articles/{articleId}
    controller: App\Controller\ArticlesController::view

create:
    path: /articles/creation
    controller: App\Controller\ArticlesController::create
